name: Compilation (Windows)

on:
  push:
    branches: [ "master" ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: (1) Checkout
      uses: actions/checkout@v3

    - name: (1.1) Debug output
      run: |
        ls
        tree

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version:      6.7.*
        cache:        true
        host:         windows
        target:       desktop
        arch:         win64_msvc2019_64
        modules:      qtconnectivity
        dir:          ${{ runner.temp }}
        setup-python: false

    - name: Set QTDIR and QtToolsPath
      shell: bash
      run: |
        echo "QTDIR=$QT_ROOT_DIR" >> "$GITHUB_ENV"
        echo "QtToolsPath=$QT_ROOT_DIR/bin" >> "$GITHUB_ENV"

    - name: Print Qt version information
      run: |
        qmake -v

    - name: Building
      run: |
        mkdir -p ${{ runner.temp }}\build
        cd ${{ runner.temp }}\build
        echo "======================================"
        echo ">> QMake pro file:"
        cat ${{ github.workspace }}/CookBook.pro | nl
        echo "======================================"
        echo ">> Extracting metadata:"
        bash ${{ github.workspace }}/meta.sh ${{ github.workspace }} "${{ github.workspace }}/src/gui/about_metadata.h"
        ls ${{ github.workspace }}/src/gui/about_metadata.h
        cat ${{ github.workspace }}/src/gui/about_metadata.h
        echo "======================================"
        echo ">> Configuring:"
        qmake -spec win32-msvc ${{ github.workspace }}/CookBook.pro
        nmake
        echo "======================================"
        echo ">> Makefile:"
        #cat Makefile | nl
        #cat Makefile.Debug | nl
        #cat Makefile.Release | nl
        echo "======================================"
        echo ">> Building:"
        make -j
        echo "======================================"

    # qt5-qmake qtbase5-dev libmtp-dev
