name: Compilation (Windows)

on:
  push:
    branches: [ "master" ]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: (1) Checkout
      uses: actions/checkout@v3

    - name: (1.1) Debug output
      run: |
        ls
        tree

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true

    - name: Print Qt version information
      run: |
        qmake -v

    - name: Building
      run: |
        mkdir -p ${{ runner.temp }}\build
        cd ${{ runner.temp }}\build
        echo "======================================"
        echo ">> QMake pro file:"
        cat ${{ github.workspace }}/CookBook.pro
        echo "======================================"
        echo ">> Configuring:"
        qmake ${{ github.workspace }}/CookBook.pro
        echo "======================================"
        echo ">> Building:"
        make -j
        echo "======================================"

    # qt5-qmake qtbase5-dev libmtp-dev
